name: nlp-sentiment-toxicity
channels:
  - pytorch
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=22.3.1
  - pytorch=2.0.1
  - torchvision
  - numpy=1.24.3
  - pandas=2.0.3
  - tqdm=4.65.0
  - scikit-learn=1.3.0
  - pip:
    - transformers==4.37.2
    - sentencepiece==0.1.99
    - fasttext==0.9.2
    - langchain==0.1.0
    - langchain-ollama==0.0.3
    - accelerate==0.25.0
    - protobuf==3.20.3
    - regex==2023.10.3
    - tokenizers==0.15.0
    - safetensors==0.4.0
    - pydantic==2.4.2
    - pydantic-core==2.10.1
    - colorama==0.4.6
    - pyarrow==14.0.1
    - optimum==1.13.2
    - einops==0.7.0 